name = "LibCEED"
uuid = "2cd74e05-b976-4426-91fa-5f1011f8952b"
version = "0.3.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
libCEED_jll = "762fde13-7596-547b-826d-8223c52d51c1"

[compat]
CEnum = "0.4"
Cassette = "0.3"
JLLWrappers = "1"
Preferences = "1"
Requires = "1"
StaticArrays = "1"
UnsafeArrays = "1"
julia = "1.6"
libCEED_jll = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
