name: ARM and IBM Power

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        compiler: [gcc-9]
        arch: [aarch64, ppc64le]
        distro: [ubuntu20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v2
    - name: Hardware setup and test libCEED
      uses: uraimo/run-on-arch-action@v2
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran-9
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        run: |
          apt-get -y update
          apt-get install -y build-essential
          apt-get install -y gfortran
          uname -a
          make info
          make -j2
          PROVE_OPTS=-v make prove -j2
