name: ARM and IBM Power

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        compiler: [gcc-11]
        arch: [aarch64, ppc64le]
        distro: [ubuntu22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Environment setup
      uses: actions/checkout@v2
    - name: Hardware setup and test libCEED
      uses: uraimo/run-on-arch-action@v2.0.7
      env:
        CC: ${{ matrix.compiler }}
        FC: gfortran-11
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu22.04
        run: |
          apt-get -y update
          apt-get install -y build-essential
          apt-get install -y gfortran
          apt-get install -y python3
          uname -a
          make info
          make -j2
          PROVE_OPTS=-v make prove -j2
